version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - .back-end-api/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build: back-end-api/.
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back-end-api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    container_name: front-end-tracker
    build: ./front-end-tracker
    volumes:
      - './front-end-tracker:/app'
      
    ports:
        - 3000:3000

  celery-beat:
    build: back-end-api/.
    command: celery -A superstonk_activity beat --loglevel=debug --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
    - ./back-end-api/:/code
    depends_on:
    - db

  celery-worker:
    build: back-end-api/.
    command: celery -A superstonk_activity worker -B
    volumes:
      - ./back-end-api/:/code
    depends_on:
      - db

  redis:
    restart: always
    image: redis:latest
    expose:
        - '6379'
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
    redisdata: