# Generated by Django 3.2.3 on 2021-05-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit_metrics', '0002_activity_metrics_subreddit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_metrics',
            name='Online_members',
            field=models.IntegerField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='activity_metrics',
            name='Total_members',
            field=models.IntegerField(max_length=1024),
        ),
    ]
