# Generated by Django 3.2.3 on 2021-05-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit_metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_metrics',
            name='Subreddit',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
