# Generated by Django 3.2.3 on 2021-05-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit_metrics', '0003_auto_20210531_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_metrics',
            name='Price',
            field=models.IntegerField(default=222.0),
            preserve_default=False,
        ),
    ]
