# Generated by Django 3.2.3 on 2021-05-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit_metrics', '0004_activity_metrics_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_metrics',
            name='Online_members',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activity_metrics',
            name='Price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='activity_metrics',
            name='Total_members',
            field=models.IntegerField(),
        ),
    ]
