# Generated by Django 3.2.3 on 2021-05-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
                ('Total_members', models.CharField(max_length=1024)),
                ('Online_members', models.CharField(max_length=1024)),
            ],
        ),
    ]
