# Generated by Django 3.2.3 on 2021-05-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit_metrics', '0005_auto_20210531_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity_metrics',
            options={'ordering': ['Created_date']},
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
                ('Subreddit_Name', models.CharField(default='', max_length=1024)),
                ('Subreddit_Link', models.CharField(default='', max_length=1024)),
                ('Subreddit_Description', models.CharField(default='', max_length=1024)),
                ('Activity_metrics', models.ManyToManyField(to='subreddit_metrics.Activity_metrics')),
            ],
            options={
                'ordering': ['Created_date'],
            },
        ),
    ]
